apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lnd
spec:
  releaseName: lnd
  chart:
    spec:
      chart: lnd
      sourceRef:
        kind: HelmRepository
        name: fold
        namespace: lnd
#      version: "0.3.8"
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: lnd-values