---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: epicworld
spec:
  chart:
    spec:
      chart: chart
      sourceRef:
        kind: GitRepository
        name: epicworld
        namespace: epicworld
  interval: 2m0s