# start with a default flux deployment
resources:
  - gotk-components.yaml

patches:
  - target:
      kind: Deployment
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: whatever
      spec:
        template:
          metadata:
            annotations:
              # Required by Kubernetes node autoscaler
              cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          spec:
            imagePullSecrets:
            - name: private-registry
            terminationGracePeriodSeconds: 60
            # Required by Pod Security Policy
            securityContext:
              runAsUser: 10000
              fsGroup: 1337
            containers:
              - name: manager
                # Required by Pod Security Policy
                securityContext:
                  readOnlyRootFilesystem: true
                  allowPrivilegeEscalation: false
                  runAsNonRoot: true
                  capabilities:
                    drop:
                      - ALL
  - target:
      kind: Deployment
      name: helm-controller
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: helm-controller
      spec:
        template:
          spec:
            containers:
            - name: manager
              resources:
                limits:
                  cpu: 500m
                  memory: 750Mi
                requests:
                  cpu: 500m
                  memory: 750Mi
  - target:
      kind: Deployment
      name: kustomize-controller
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: kustomize-controller
      spec:
        template:
          spec:
            containers:
            - name: manager
              resources:
                limits:
                  cpu: 100m
                  memory: 200Mi
                requests:
                  cpu: 100m
                  memory: 200Mi
  - target:
      kind: Deployment
      name: notification-controller
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: notification-controller
      spec:
        template:
          spec:
            containers:
            - name: manager
              resources:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 100m
                  memory: 100Mi
  - target:
      kind: Deployment
      name: source-controller
    patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: source-controller
      spec:
        template:
          spec:
            containers:
            - name: manager
              resources:
                limits:
                  cpu: 100m
                  memory: 150Mi
                requests:
                  cpu: 100m
                  memory: 150Mi                                
